name: 2025-ictv-vmr-database
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake>=8,<9
  - screed>1,<2
  - pandas>=2.2.3
  - openpyxl
  - sourmash>=4.8.14,<5
  - sourmash_plugin_branchwater>=0.9.13,<1
  - sourmash_plugin_directsketch>=0.6.0,<1
  - blast=2.16.0
  - tenacity
