sourmash_params:
  DNA:
    ksize: [21, 31]
    scaled: [50,100] # 1,10,1000
    threshold_bp: 0
  skipm1n3:
    ksize: [15,18,21,24,27]
    scaled: [50,100] #1,10 1,5,10,1000
    threshold_bp: 0
  skipm2n3:
    ksize: [15,18,21,24,27]
    scaled: [50,100] #1,10,1000
    threshold_bp: 0
